export const inventoryList = [
    {
        "itemName":"bread",
        "itemPrice":4.32,
        "itemMarkdown":{
            "decrease":.50,
            "limit":5
        },
        "itemSpecial":{
            "type":"buy 2, get 1 free",
            "limit":6
        }
    },
    {
        "itemName":"soup",
        "itemPrice":1,
        "itemMarkdown":{
            "decrease":.50,
            "limit":5
        },
        "itemSpecial":{
            "type":"buy 2, get 1 free",
            "limit":6
        }
    },
    {
        "itemName":"beef",
        "itemPrice":2,
        "itemMarkdown":{
            "decrease":.50,
            "limit":5
        },
        "itemSpecial":{
            "type":"buy 2, get 1 free",
            "limit":6
        }
    }
]
export const inventoryListA = [
    {
        "itemName":"whole wheat bread",
        "itemPrice":4.32,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"chips",
        "itemPrice":3.56,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"soup",
        "itemPrice":1,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"beef",
        "itemPrice":2,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    }
]
export const inventoryListB = [
    {
        "itemName":"whole wheat bread",
        "itemPrice":4.32,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"chips",
        "itemPrice":3.56,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"soup",
        "itemPrice":1,
        "itemMarkdown":{
            "decrease":.50,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"beef",
        "itemPrice":2,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    }
]
export const inventoryListC = [
    {
        "itemName":"whole wheat bread",
        "itemPrice":4.32,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"chips",
        "itemPrice":3.56,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"soup",
        "itemPrice":1,
        "itemMarkdown":{
            "decrease":.50,
            "limit":2
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"beef",
        "itemPrice":2,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    }
]
export const inventoryListD = [
    {
        "itemName":"whole wheat bread",
        "itemPrice":4.32,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"chips",
        "itemPrice":3.56,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"soup",
        "itemPrice":1,
        "itemMarkdown":{
            "decrease":.50,
            "limit":2
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"beef",
        "itemPrice":2,
        "itemMarkdown":{
            "decrease": 1,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    }
]
export const inventoryListE = [
    {
        "itemName":"whole wheat bread",
        "itemPrice":4.32,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"chips",
        "itemPrice":3.56,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"soup",
        "itemPrice":1,
        "itemMarkdown":{
            "decrease":.50,
            "limit":2
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"beef",
        "itemPrice":2,
        "itemMarkdown":{
            "decrease": 1,
            "limit":2
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    }
]
export const inventoryListF = [
    {
        "itemName":"whole wheat bread",
        "itemPrice":4.32,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"chips",
        "itemPrice":3.56,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"soup",
        "itemPrice":1,
        "itemMarkdown":{
            "decrease":.50,
            "limit":2
        },
        "itemSpecial":{
            "type":null,
            "limit":null
        }
    },
    {
        "itemName":"beef",
        "itemPrice":2,
        "itemMarkdown":{
            "decrease": 0,
            "limit":null
        },
        "itemSpecial":{
            "type":"Buy 2 get 1 free",
            "limit":6
        }
    }
]
export const scannedItems = [
    {
        "itemName":"whole wheat bread",
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"chips",
        "quantity":2,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"beef",
        "quantity":1,
        "weight":1.5
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    }
]
export const scannedItemsA = [
    {
        "itemName":"whole wheat bread",
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"chips",
        "quantity":2,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"beef",
        "quantity":1,
        "weight":1.5
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    },
    ,
    {
        "itemName":"beef",
        "quantity":1,
        "weight":3.5
    },
    {
        "itemName":"beef",
        "quantity":1,
        "weight":4
    }
]
export const scannedItemsB = [
    {
        "itemName":"soup", 
        "quantity":5,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":3,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":9,
        "weight":null
    },
    {
        "itemName":"soup", 
        "quantity":1,
        "weight":null
    }
]
export const scannedItemsC = [
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    }
]
export const scannedItemsD = [
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },{
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    },
    {
        "itemName":"beef", 
        "quantity":1,
        "weight":1
    }
]
export const specials = [
    {
        "specialName":"Buy 2 get 1 free",
        "A":2,//buy
        "B":1,//get
        "C":100//% off
    }, 
    {
        "specialName":"Buy 1 get 1 free",
        "A":1,//buy
        "B":1,//get
        "C":100//% off
    },
    {
        "specialName":"Buy 3 for $7",
        "A":3,//buy
        "B":7//for $
    }
]